[common] instance_id="rea-lab-001" interval_secs=5 max_event_bytes=131072
[collectors] top_n_procs=5 win_eventlog_channels=["System","Application"] win_eventlog_rps=10
[output] mode="stdout" file_path="C:\\ProgramData\\REA\\logs\\agent.jsonl" rotate_bytes=10485760
[networking]
enabled=false
endpoint="https://127.0.0.1:8443/ingest"
batch_max_events=200
batch_max_bytes=524288
flush_interval_ms=2000
queue_dir="C:\\ProgramData\\REA\\queue"
queue_max_bytes=52428800
ca_cert="C:\\ProgramData\\REA\\tls\\ca.crt"
client_cert="C:\\ProgramData\\REA\\tls\\client.crt"
client_key="C:\\ProgramData\\REA\\tls\\client.key"
spki_pin_sha256=""
compression="zstd"
retry_budget=8
[status] port=0
